andywer/webpack-blocks

packages/babel6/CHANGELOG.md
packages/babel6/index.js
packages/babel6/package.json
packages/css-modules/CHANGELOG.md
packages/css-modules/index.js
packages/css-modules/package.json
packages/postcss/CHANGELOG.md
packages/postcss/index.js
packages/postcss/package.json
packages/sass/CHANGELOG.md
packages/sass/index.js
packages/sass/package.json
packages/webpack/CHANGELOG.md
packages/webpack/__tests__/integration.test.js
packages/webpack/index.js
packages/webpack/package.json

Use explicit `-loader` suffix on loaders, since webpack 2 is going to enforce this convention.
Also removed empty string from `resolve.extensions`.

Explicit -loader suffix

---

packages/webpack/__tests__/integration.test.js
packages/webpack/index.js

When trying to use a file including the extension, it will crash unless you have an empty extension. It is a pretty common Webpack configuration.
Before the fix this configuration was throwing an error: 
```js
const path = require('path');
const { createConfig, entryPoint, env, setOutput, webpack } = require('@webpack-blocks/webpack');
const babel = require('@webpack-blocks/babel6');
const config = createConfig([
entryPoint('./src/index.js'),
setOutput('./build/bundle.js'),
babel(),
]);
module.exports = config;
```
**ERROR in multi main
Module not found: Error: Cannot resolve 'file' or 'directory' ./test.js in /private/var/git/thereactivestack/webpack-blocks-test/src
@ multi main**
But it was working if I was using `./src/index` instead without the extension.

Add empty extension to the default extensions

---

packages/core/src/__tests__/entryPoint.test.js
packages/dev-server/__tests__/devServer.test.js
packages/dev-server/index.js
packages/dev-server/package.json
packages/webpack/__tests__/entryPoint.test.js
packages/webpack/__tests__/integration.test.js
packages/webpack/index.js

When adding `devServer` on an entry like that: `entryPoint({ app: './src/index' })`, it would override the whole entry point by only the devServer.
This is fixing the way the entry is merged. 
Here is my whole webpack.config.js:
```js
const path = require('path');
const { createConfig, env, entryPoint, setOutput, addPlugins, setDevTool, webpack } = require('@webpack-blocks/webpack');
const babel = require('@webpack-blocks/babel6');
const cssModules = require('@webpack-blocks/css-modules');
const extractText = require('@webpack-blocks/extract-text');
const { StatsWriterPlugin } = require('webpack-stats-plugin');
const devServer = require('@webpack-blocks/dev-server');
const development = [
setOutput({ filename: '[name].js' }),
setDevTool('eval'),
addPlugins([
new webpack.DefinePlugin({ …
```

Fix dev-server when using named entries

---

packages/extract-text/CHANGELOG.md
packages/extract-text/README.md
packages/extract-text/index.js
packages/extract-text/package.json

Didn't work before when there were more than 2 webpack loaders assigned to a file type.
Also added another parameter, so you can now apply the ExtractTextPlugin on other file types as CSS (like SASS, for instance) as well.

Bugfix: Fix extract-text block

---

packages/webpack/README.md
packages/webpack/__e2e-fixtures__/babel-postcss-extract-text/webpack.config.js
packages/webpack/__tests__/defineConstants.test.js
packages/webpack/index.js

Now that we have got `pre`/`post` hooks, `context` and `group()` it is easy to implement `defineConstants`.
Resolves #17.

Implement `defineConstants`

---

packages/webpack2/CHANGELOG.md
packages/webpack2/__tests__/integration.test.js
packages/webpack2/index.js
packages/webpack2/package.json

Webpack 2 comes with a default `json-loader` config. We will just use that by default.
Resolves #63. Read that issue for details.

Webpack2: Remove json-loader

---

packages/postcss/CHANGELOG.md
packages/postcss/README.md
packages/postcss/index.js
packages/postcss/package.json

Adds support for custom PostCSS options (`parser`, `stringifier`, `syntax`).
@nightgrey This has been part of your PR #69 as well. I separated it, since this feature works independently from the webpack 2 changes. Feel free to review :)

PostCSS custom options

---

packages/postcss/CHANGELOG.md
packages/postcss/README.md
packages/postcss/index.js
packages/postcss/package.json
packages/webpack2/__e2e-fixtures__/babel-postcss-extract-text/postcss.config.js
packages/webpack2/__e2e-fixtures__/babel-postcss-extract-text/webpack.config.js

You could not configure the PostCSS plugins from within your webpack config before when using webpack 2. This has now been fixed. No difference in usage, just update the `postcss` block.
Fixes #68. Replaces #69.

Critical fix: Make PostCSS inlined plugin config work with webpack 2

---

packages/core/src/index.js

I hope that makes the `invokeConfigSetters` code and its usage a little easier to understand.
Also fixes a minor issue I encountered when using `group()`/`env()`:
The webpack config object that was passed to blocks as 2nd parameter contained duplicate prop values when blocks where used in a `group()`/`env()`. Did not cause any bugs yet, though AFAIK.
@eXon Did I succeed to improve the code's readability or didn't I? 😅

Slightly changed `invokeConfigSetters` code

---

README.md
packages/webpack/CHANGELOG.md
packages/webpack/README.md
packages/webpack/__tests__/integration.test.js
packages/webpack/index.js
packages/webpack2/CHANGELOG.md
packages/webpack2/README.md
packages/webpack2/__tests__/integration.test.js
packages/webpack2/index.js

Adds `createConfig.vanilla()` to opt-out of the usual defaults that `createConfig()` normally sets automatically.
Fixes #80.

Vanilla createConfig()

---

packages/css-modules/CHANGELOG.md
packages/css-modules/index.js
packages/postcss/CHANGELOG.md
packages/postcss/index.js
packages/webpack/CHANGELOG.md
packages/webpack/__tests__/integration.test.js
packages/webpack/index.js
packages/webpack2/CHANGELOG.md
packages/webpack2/__tests__/integration.test.js
packages/webpack2/index.js

The `node_modules` directory should not be excluded from the css-loader (esp. not implicitly).
Fixes #83.

Drop `node_modules/` exclusion from default css-loader

---

README.md
packages/tslint/CHANGELOG.md
packages/tslint/README.md
packages/tslint/index.js
packages/tslint/package.json
packages/webpack/__e2e-fixtures__/typescript/app.ts
packages/webpack/__e2e-fixtures__/typescript/tslint.json
packages/webpack/__e2e-fixtures__/typescript/webpack.config.js
packages/webpack/package.json
packages/webpack2/__e2e-fixtures__/typescript/app.ts
packages/webpack2/__e2e-fixtures__/typescript/tslint.json
packages/webpack2/__e2e-fixtures__/typescript/webpack.config.js
packages/webpack2/package.json

for all typescript linting needs :)

add tslint block

---

README.md

Turns the preset section into a FAQ item (making the README visually shorter), highlights the ease of writing custom blocks. Also removes an obsolete line from the "0.3 update" section.
@eXon @dmitriz @jvanbruegge Any feedback? 😉

Restructure README a bit

---

README.md

Succeeds #65.
Changes:
* `npm install @webpack-blocks/webpack2 ...`
* "switching to webpack 2" section heading renamed
* "group()" sample uses webpack2

README: Use webpack2 consequently

---

packages/postcss/index.js

**Current behavior**
This:
```js
createConfig([
postcss(),
])
```
produces a warning “PostCSS Config could not be loaded. Please check your PostCSS Config”.
But this:
```js
createConfig([
postcss([]),  // Empty plugins array
])
```
works fine.
This pull request removes the warning.

Fix optionalness of plugins param

---

packages/webpack-common/src/__tests__/devServer.integration.test.js
packages/webpack-common/src/devServer.js
packages/webpack/__tests__/integration.test.js
packages/webpack2/__tests__/integration.test.js

Hello :-)
I think that `webpack-blocks` don't need to worry about `webpack/hot/only-dev-server`, because users of `webpack-blocks` can self use `hotOnly` and `hot` options of `webpack-dev-server` (for example switch off it)
I setted options `hotOnly` by default for backwards compatibility (`hot` been setted previously)

webpack-common: hotOnly by default for devServer

---

packages/postcss/index.js

Hello :-)
I found that `postcss.config.js` did't loading because `@webpack-blocks/postcss` create empty `postcss` (https://github.com/andywer/webpack-blocks/blob/master/packages/postcss/index.js#L55)

postcss: fix loading of postcss.config.js and etc

---

packages/typescript/index.js

The option is called `configFileName` for the loader, but `tsconfig` for the plugin

Fix tsconfig option name

---

packages/core/lib/__tests__/createConfig.test.js
packages/core/lib/index.js
packages/webpack/__tests__/devServer.integration.test.js
packages/webpack/__tests__/integration.test.js

Otherwise blocks will overwrite them instead of extending. For example I have full screen of nasty errors with `typescript` and `devSever`:
<details>
```
ERROR in multi (webpack)-dev-server/client?http://localhost:3423 webpack/hot/only-dev-server ./src/ui/app/index.ts
Module not found: Error: Can't resolve 'webpack/hot/only-dev-server' in '/Users/sapegin/izumi/nodejs-defaults'
@ multi (webpack)-dev-server/client?http://localhost:3423 webpack/hot/only-dev-server ./src/ui/app/index.ts
ERROR in (webpack)-dev-server/client?http://localhost:3423
Module not found: Error: Can't resolve './socket' in '/Users/sapegin/izumi/nodejs-defaults/node_modules/webpack-dev-server/client'
@ (webpack)-dev-server/client?http://localhost:3423 4:13-32
@ multi (webpack)-dev-server/client?http://localhost:3423 …
```

Explicitly define default extensions

---

packages/core/lib/index.js

Validate `configSetters` in all public API functions.

Better error handling of configSetters param

---

packages/webpack/__tests__/integration.test.js
packages/webpack/index.js
packages/webpack/package.json

Allow custom extensions configurations, like
```js
resolve({
extensions: ['.custom.js']
})
```
so that 
```js 
import foo from './foo'
```
first checks `./foo.custom.js` before falling back to `./foo.js`
Closes #176

Fix resolve block to prefer custom extensions over defaults

---

packages/core/CHANGELOG.md
packages/core/lib/index.js
packages/webpack/CHANGELOG.md
packages/webpack/index.js
packages/webpack/package.json

In case you passed an invalid setter. One of the #171 tasks.

Improve `createConfig()` error message

---

packages/extract-text/CHANGELOG.md
packages/extract-text/README.md
packages/extract-text/package-lock.json
packages/extract-text/package.json

We need to make sure we have a version of `extractText` block that *still* works in webpack 2, which should be published before merging this PR, if have any unpublished changes.
Probably I should update webpack peer dependency in all other blocks.
Probably we should update the readme to say which versions of the block work in which versions of webpack.
Closes #190.

[WIP] Update extract-text-webpack-plugin to v3, drop webpack 2 support

---

packages/babel/__tests__/babel.test.js
packages/core/CHANGELOG.md
packages/core/lib/__tests__/match.test.js
packages/core/lib/match.js

Currently it's not possible to pass [webpack rule options](https://webpack.js.org/configuration/module/) other than `exclude` and `include` to blocks. Also there is no way to remove default options from blocks (for example the `exclude` in the `babel` block).
This PR fixes both problems.

Change match() to pass all webpack rule options to context.

---

.travis.yml

Should fix Travis CI sometimes failing with "No output received in the last 10m" (esp. on node 6).

Increase cancel on "no output" timeout

---

README.md
packages/eslint/CHANGELOG.md
packages/eslint/README.md
packages/eslint/__tests__/eslint.test.js
packages/eslint/index.js
packages/eslint/package.json

Almost like the `tslint` block, but for JavaScript.

Support for ESLint

---

packages/babel/CHANGELOG.md
packages/babel/README.md
packages/babel/package.json
packages/sample-app/.babelrc
packages/sample-app/package.json
packages/webpack/package.json
yarn.lock

Add support for Babel 7 (for 2.0 webpack-blocks release).  Supercedes PR #257 which was out-of-date.

Support for babel-loader@8 / babel@7

---

lerna.json
package.json
packages/sample-app/.eslintrc.json
yarn.lock

Notable:
- `lerna` got a major bump to v3.
- `yarn` since 1.10 adds an `integrity` field to `yarn.lock`. I've made sure older versions don't remove it.

Upgrade root deps to latest

---

packages/sass/CHANGELOG.md
packages/sass/README.md
packages/sass/__tests__/integration.test.js
packages/sass/index.js
packages/webpack/__e2e-fixtures__/postcss-sass-sourcemaps/webpack.config.js
packages/webpack/__e2e-fixtures__/sass-extract-text/webpack.config.js
packages/webpack/__tests__/integration.test.js

Followup of discussion in #293

Remove css-loader and style-loader from the sass block

---

packages/assets/package.json
packages/babel/package.json
packages/dev-server/package.json
packages/eslint/package.json
packages/extract-text/package.json
packages/postcss/package.json
packages/sass/package.json
packages/tslint/package.json
packages/typescript/package.json
packages/uglify/package.json

Follow up on #305 - since the new version was published without a prerelease tag, this warning was reintroduced. Wish I had thought of this before I asked you to publish a new version!
Now that the version has no prerelease tags, this shouldn't need to be updated again unless another prerelease tag is added.

Remove -rc tags to fix pesky peer deps warnings

---

packages/babel/package.json

Changes the peer dependencies of @webpack-blocks/babel from `babel-core` to `@babel/core`

Change the peer dependencies for babel package
