- packages/babel6/README.md
- packages/core/README.md
- packages/css-modules/README.md
- packages/dev-server/README.md
- packages/extract-text/README.md
- packages/postcss/README.md
- packages/sass/README.md
- packages/webpack/README.md
Add version badges to package readme files and add some package API documentation.
> Improve package READMEs

- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/__tests__/env.test.js
- packages/core/src/index.js
> Bugfix: env() merges too much

- packages/babel6/index.js
- packages/core/src/createFileTypesMapping.js
- packages/core/src/index.js
- packages/css-modules/index.js
- packages/dev-server/index.js
- packages/extract-text/index.js
- packages/postcss/index.js
- packages/sass/index.js
- packages/webpack/index.js
Follow-up of #33. Need to update #41 as well.
> Rename `context.fileTypes` => `context.fileType`

- packages/babel6/CHANGELOG.md
- packages/babel6/README.md
- packages/babel6/__tests__/babel6.test.js
- packages/babel6/index.js
- packages/babel6/package.json
- packages/webpack/__tests__/integration.test.js
- packages/webpack/package.json
> Make Babel presets/plugins configurable by block params

- packages/dev-server/README.md
> Remove pitfalls block

- packages/core/package.json
- packages/webpack-common/src/extractText.js
- packages/webpack/__tests__/integration.test.js
- packages/webpack2/__tests__/integration.test.js
Splitted this from #59 to separate concerns.
Might already fix #76.
> Upgrade to webpack-merge 2.x

- packages/core/CHANGELOG.md
- packages/core/src/defaultFileTypes.js
> Add MIME type `text/x-less` to file types

- README.md
- packages/core/src/defaultFileTypes.js
- packages/typescript/CHANGELOG.md
- packages/typescript/README.md
- packages/typescript/__tests__/typescript.test.js
- packages/typescript/index.js
- packages/typescript/package.json
- packages/webpack/__e2e-fixtures__/typescript/app.ts
- packages/webpack/__e2e-fixtures__/typescript/webpack.config.js
- packages/webpack/__tests__/end-to-end.test.js
- packages/webpack/package.json
- packages/webpack2/__e2e-fixtures__/typescript/app.ts
- packages/webpack2/__e2e-fixtures__/typescript/webpack.config.js
- packages/webpack2/__tests__/end-to-end.test.js
- packages/webpack2/package.json
Adds a typescript block for compiling typescript and typescript react (.ts and .tsx) with webpack.
Tests are passing.
> add webpack typescript block

- packages/webpack/__tests__/integration.test.js
- packages/webpack/index.js
- packages/webpack2/__e2e-fixtures__/babel-postcss-extract-text/webpack.config.js
- packages/webpack2/__tests__/integration.test.js
- packages/webpack2/index.js
> Vanilla config: Add empty loaders/plugins array

- packages/webpack/README.md
- packages/webpack2/README.md
> Document all exported functions of `webpack` & `webpack2`

- packages/core/CHANGELOG.md
- packages/core/README.md
- packages/core/src/__tests__/createConfig.test.js
- packages/core/src/index.js
- packages/webpack-common/CHANGELOG.md
- packages/webpack-common/src/__tests__/defineConstants.test.js
- packages/webpack-common/src/__tests__/devServer.integration.test.js
- packages/webpack-common/src/__tests__/parseVersion.test.js
- packages/webpack-common/src/index.js
- packages/webpack-common/src/parseVersion.js
- packages/webpack/CHANGELOG.md
- packages/webpack/__tests__/integration.test.js
- packages/webpack/index.js
- packages/webpack2/CHANGELOG.md
- packages/webpack2/__tests__/integration.test.js
- packages/webpack2/index.js
This PR is the successor of #96 (thanks, @jvanbruegge!). As discussed this PR comes with a few changes (`parseVersion()` slightly changed and in its own file, more tests)
Resolves #93.
> Add webpackVersion to context

- packages/babel6/CHANGELOG.md
- packages/babel6/__tests__/babel6.test.js
- packages/babel6/index.js
- packages/webpack/__tests__/integration.test.js
- packages/webpack2/__tests__/integration.test.js
Im using this block for a boilerplate and because of windows' use of backslash as directory seperator this regex fails
> Fix default exclude on windows

- packages/babel6/package.json
- packages/core/package.json
- packages/typescript/package.json
- packages/webpack-common/package.json
- packages/webpack-common/src/__tests__/devServer.integration.test.js
- packages/webpack/package.json
- packages/webpack2/package.json
> Update AVA to 0.18.0

- packages/babel6/package.json
- packages/core/package.json
- packages/css-modules/package.json
- packages/dev-server/package.json
- packages/dev-server2/package.json
- packages/extract-text/package.json
- packages/extract-text2/package.json
- packages/postcss/package.json
- packages/sass/package.json
- packages/tslint/package.json
- packages/typescript/package.json
- packages/webpack-common/package.json
- packages/webpack/package.json
- packages/webpack2/package.json
Hi @andywer! Webpack Blocks is such an awesome idea. I've found it a bit difficult to find the various available blocks on npmjs.com though, so here are some keywords! :)
> Add package keywords for npm discoverability

- packages/postcss/CHANGELOG.md
- packages/postcss/index.js
- packages/webpack2/__e2e-fixtures__/postcss-sass-sourcemaps/styles.sass
- packages/webpack2/__e2e-fixtures__/postcss-sass-sourcemaps/webpack.config.js
- packages/webpack2/__tests__/end-to-end.test.js
Fixes #116. Introduces a regression test as well.
> Fix strange PostCSS/SASS issue

- packages/webpack/CHANGELOG.md
- packages/webpack/index.js
- packages/webpack/package.json
- packages/webpack2/CHANGELOG.md
- packages/webpack2/index.js
- packages/webpack2/package.json
> Throw error if `createConfig()` is used incorrectly.

- README.md
- docs/BLOCK-CREATION.md
- packages/babel6/__tests__/babel6.test.js
- packages/babel6/index.js
- packages/core/package.json
- packages/core/src/__tests__/createConfig.test.js
- packages/core/src/blockUtils.js
- packages/core/src/index.js
- packages/css-modules/index.js
- packages/dev-server/index.js
- packages/extract-text/index.js
- packages/extract-text/package.json
- packages/postcss/index.js
- packages/sass/index.js
- packages/tslint/index.js
- packages/typescript/__tests__/typescript.test.js
- packages/typescript/index.js
- packages/webpack/__tests__/devServer.integration.test.js
- packages/webpack/__tests__/integration.test.js
- packages/webpack/index.js
- test-app/package.json
~~This is still WIP until we have a solution for https://github.com/andywer/webpack-blocks/issues/34#issuecomment-282934444~~
This is based on #128 and should be good to go once that is merged.
> Port to webpack 2.0 config style

- test-app/README.md
Fix broken link to webpack config.
> Update README.md from test-app

- README.md
Provide a prominent link to the 1.0 release branch and the feedback request issue.
> Update main readme in master branch

- packages/postcss/README.md
- packages/postcss/index.js
> PostCSS: Add include option and document loader options in block readme

- packages/dev-server/index.js
- packages/webpack/__tests__/devServer.integration.test.js
> Port @bkonkle's PR #129 to 1.0: Add NamedModulesPlugin to dev server

- packages/webpack/README.md
- packages/webpack/index.js
> Add resolve block (1.0)

- packages/webpack-common/src/webpack.js
- packages/webpack/README.md
- packages/webpack/index.js
- packages/webpack2/README.md
- packages/webpack2/index.js
> Add resolve block

- .travis.yml
- packages/sass/CHANGELOG.md
- packages/sass/package.json
- packages/webpack/package.json
- packages/webpack2/package.json
> v0.4: Update node-sass & sass-loader

- packages/webpack/package.json
> Make webpack a peer dependency, make webpack 3 compatible

- packages/webpack/README.md
- packages/webpack/index.js
> Drop webpack export

- packages/sass/README.md
Describe usage with CSS modules & PostCSS.
> Update SASS block readme

- lerna.json
- packages/webpack-blocks/CHANGELOG.md
- packages/webpack-blocks/package.json
- packages/webpack/CHANGELOG.md
- packages/webpack/package.json
Changes since v1.0.0-beta:
- webpack as a peer dependency
- officially webpack v3 compatible
> v1.0.0-beta.2

- packages/dev-server/CHANGELOG.md
- packages/dev-server/package.json
- packages/webpack-blocks/CHANGELOG.md
- packages/webpack-blocks/package.json
Ships update of `@webpack-blocks/dev-server` webpack dependency. So this is practically a hotfix for v1.0.0-beta.2.
> v1.0.0-beta.3

- packages/webpack/__e2e-fixtures__/sass-css-modules/src/index.js
- packages/webpack/__e2e-fixtures__/sass-css-modules/src/styles.scss
- packages/webpack/__e2e-fixtures__/sass-css-modules/webpack.config.js
- packages/webpack/__tests__/end-to-end.test.js
> Add SASS with CSS modules end-to-end test

- package-lock.json
- packages/assets/package-lock.json
- packages/assets/package.json
- packages/babel6/package-lock.json
- packages/babel6/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/dev-server/package-lock.json
- packages/elm/package-lock.json
- packages/extract-text/package-lock.json
- packages/extract-text/package.json
- packages/postcss/package-lock.json
- packages/sass/package-lock.json
- packages/sass/package.json
- packages/tslint/package-lock.json
- packages/tslint/package.json
- packages/typescript/package-lock.json
- packages/typescript/package.json
- packages/webpack-blocks/package-lock.json
- packages/webpack/package-lock.json
- packages/webpack/package.json
`package-lock.json` is a new feature of npm 5 and works roughly like `yarn.lock`.
> Add package-lock.json files, update dependencies

- CONTRIBUTING.md
> Add very basic contribution guidelines

- packages/uglify/CHANGELOG.md
- packages/uglify/README.md
- packages/uglify/__tests__/uglify.test.js
- packages/uglify/index.js
- packages/uglify/package-lock.json
- packages/uglify/package.json
- packages/webpack-blocks/CHANGELOG.md
- packages/webpack-blocks/README.md
- packages/webpack-blocks/index.js
- packages/webpack-blocks/package.json
- test-app/webpack.config.babel.js
Should I add it to `webpack-blocks` package too?
> Add UglifyJS block

- README.md
- Remove unnecessary just, simple, etc.
- Try to make the project description more clear, simple and in user’s world
- Add / tweak examples a bit
- Just a few other simple and easy tweaks ;-)
> Attempt to improve the readme

- packages/core/CHANGELOG.md
- packages/core/lib/__tests__/createConfig.test.js
- packages/core/lib/index.js
- packages/dev-server/CHANGELOG.md
- packages/dev-server/index.js
- packages/webpack/__tests__/devServer.integration.test.js
- packages/webpack/__tests__/integration.test.js
- test-app/package.json
Do not print long list of chunks etc. on build.
> Less noisy base config

- README.md
- List of third-party blocks
- Fix title casing
- Update TOC
- Add missed Elm block
> Add a list of third-party blocks

- STYLE_GUIDE.md
Feel free to suggest changes. Did I miss something?
> Add a style guide

- README.md
- packages/assets/README.md
- packages/babel6/README.md
- packages/core/README.md
- packages/dev-server/README.md
- packages/elm/README.md
- packages/extract-text/README.md
- packages/postcss/README.md
- packages/sass/README.md
- packages/tslint/README.md
- packages/typescript/README.md
- packages/uglify/README.md
- packages/webpack-blocks/README.md
- packages/webpack/README.md
> Add Gitter badge

- test-app/package.json
Update webpack-blocks to have the uglify block.
> Fix test app

- packages/extract-text/README.md
- packages/sass/README.md
- packages/webpack-blocks/README.md
- packages/webpack/README.md
- More realistic examples
- Use extactText only in production
- Add missed imports
- Simplify text
- Remove deprecated argument of extractText
> Improve styles docs a bit

- README.md
- packages/webpack-blocks/README.md
- packages/webpack/README.md
> Webpack is no longer exported from webpack-blocks package

- packages/webpack/CHANGELOG.md
- packages/webpack/README.md
- packages/webpack/index.js
- packages/webpack/lib/__tests__/setEnv.test.js
- packages/webpack/lib/defineConstants.js
- packages/webpack/lib/setEnv.js
Added a `setEnv` block as per discussion. Resolves #201
> Add setEnv block

- packages/dev-server/CHANGELOG.md
- packages/dev-server/README.md
- packages/dev-server/index.js
- packages/dev-server/package-lock.json
Fixes #209 
Closes #56, Closes #131
> Remove reactHot from the devServer block

- packages/postcss/CHANGELOG.md
- packages/postcss/README.md
- packages/postcss/__tests__/integration.test.js
- packages/postcss/index.js
- packages/postcss/package-lock.json
- packages/postcss/package.json
- packages/sass/CHANGELOG.md
- packages/sass/README.md
- packages/sass/__tests__/integration.test.js
- packages/sass/index.js
- packages/sass/package-lock.json
- packages/sass/package.json
- packages/webpack-blocks/README.md
- packages/webpack/__tests__/integration.test.js
For consistency with the `css` block.
> Add minimize option to postcss and sass blocks

- packages/postcss/CHANGELOG.md
- packages/postcss/README.md
- packages/postcss/__tests__/integration.test.js
- packages/postcss/index.js
- packages/webpack/__e2e-fixtures__/babel-postcss-extract-text/webpack.config.js
- packages/webpack/__e2e-fixtures__/postcss-sass-sourcemaps/webpack.config.js
**This is a breaking change**
Also do not use LoaderOptionsPlugin and remove a hack for sass-loader that is no longer relevant.
> PostCSS: Remove plugins argument

- README.md
- docs/BLOCK-CREATION.md
And fix a link in one of them ;-)
> Use markdown-toc to generate TOCs

- test-app/package-lock.json
- test-app/package.json
Adding `cross-env` to make the test app cross platform.
Closes #215.
> Test app cross env

- packages/assets/CHANGELOG.md
- packages/assets/README.md
- packages/assets/__tests__/css-modules.test.js
- packages/assets/lib/css.js
- packages/assets/package-lock.json
- packages/assets/package.json
- packages/postcss/__tests__/integration.test.js
- packages/sass/__tests__/integration.test.js
- packages/webpack/__tests__/integration.test.js
~WIP because I haven't updated docs yet.~ Just wanted to get some feedback.
Changes:
- added `styleLoader` option to both `css` and `css.modules` blocks
- if it's `false` a `style-loader` won't be added
- added tests for `styleLoader` and `css.modules`
> CSS: Allow to pass options to style-loader and allow to remove it from loaders

- packages/dev-server/package-lock.json
- packages/dev-server/package.json
> Update webpack-dev-server to v2.9

- README.md
> Add webpack-blocks-less

- packages/typescript/README.md
- packages/webpack/__e2e-fixtures__/typescript/tsconfig.json
- packages/webpack/__e2e-fixtures__/typescript/webpack.config.js
That should fix the typescript end-to-end tests.
> Fix typescript tests

- packages/dev-server/CHANGELOG.md
- packages/dev-server/README.md
- packages/dev-server/index.js
- packages/sample-app/webpack.config.babel.js
- packages/webpack/__tests__/integration.test.js
It doesn't do much and adds unnecessary complexity.
> Remove proxy() from the dev-server block

- README.md
- docs/MIGRATION-GUIDE.md
- packages/assets/README.md
- packages/babel/README.md
- packages/core/CHANGELOG.md
- packages/core/lib/__tests__/match.test.js
- packages/core/lib/match.js
- packages/postcss/README.md
- packages/sass/README.md
- packages/webpack/README.md
> Support negation globs in match()

- README.md
- packages/core/CHANGELOG.md
- packages/core/lib/__tests__/when.test.js
- packages/core/lib/index.js
- packages/core/lib/when.js
- packages/webpack/CHANGELOG.md
- packages/webpack/README.md
- packages/webpack/index.js
Adds a `when()` block to accept any conditional, as proposed in #242 .
I haven't reimplemented any other blocks (like `env()`) to use this one.
> Add when() block

- packages/webpack/README.md
> Update devtool docs

- README.md
> Fix PostCSS block usage
